# NumPy Module – Methods Demo & Hands-on Exercises


In [2]:
!pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.4 MB 939.2 kB/s eta 0:00:13
   -- ------------------------------------- 0.8/12.4 MB 1.0 MB/s eta 0:00:12
   ---- ----------------------------------- 1.3/12.4 MB 1.3 MB/s eta 0:00:09
   ----- ---------------------------------- 1.6/12.4 MB 1.3 MB/s eta 0:00:09
   ----- ---------------------------------- 1.8/12.4 MB 1.3 MB/s eta 0:00:09
   ------ --------------------------------- 2.1/12.4 MB 1.3 MB/s eta 0:00:09
   ------- -------------------------------- 2.4/12.4 MB 1.3 MB/s eta 0:00:08
   -------- ------------------------------- 2.6/12.4 MB 1.3 MB/s eta 0:00:08
   -------- ------------------------------- 2.6/12.4 MB 1.3 MB/s eta 0:00:08
   --------- ------------

In [3]:
import numpy as np
print(np.__version__)

2.4.2


## 1. Creating Arrays

In [15]:
#a = np.array([10, 20, 30, 40])
#b = np.zeros(5)
#c = np.ones((1,3))
#d = np.arange(1, 11, 2)
e = np.linspace(0, 1, 4)
#a, b, c, d, e
e

array([0.        , 0.33333333, 0.66666667, 1.        ])

## 2. Array Properties

In [18]:
arr = np.array([[1,2,3],[4,5,6]])
#arr.shape, 
#arr.size, 
arr.ndim, 
#arr.dtype

(2,)

## 3. Reshape & Flatten

In [22]:
x = np.arange(1, 13)

#x.reshape(2,6) 
#x.reshape(3,4) 
x.reshape(3,4).flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## 4. Mathematical Operations (Product Prices)

In [ ]:
prices = np.array([1000, 1500, 2000, 2500])
prices * 0.9

## 5. Statistics (Payments)

In [23]:
payments = np.array([500, 1200, 800, 1500, 2000])
np.sum(payments), 
np.mean(payments),
np.max(payments), 
np.min(payments)

np.int64(500)

## 6. Indexing & Slicing

In [29]:
arr = np.array([10,20,30,40,50])
arr[2:-3]

array([], dtype=int64)

## 7. Boolean Masking (Orders)

In [30]:
orders = np.array([500, 1200, 300, 1800, 2500])
orders[orders > 1000]

array([1200, 1800, 2500])

## 8. Sorting & Unique

In [36]:
arr1 = np.array([5,3,2,8,2,9,1,10,5,6,6])
#np.sort(arr), 
np.unique(arr1)

array([ 1,  2,  3,  5,  6,  8,  9, 10])

## 9. Hands-on Exercises

1. Create an array of 10 product prices and apply 15% discount
2. Filter orders greater than 1000
3. Create 3x3 matrix and calculate row-wise & column-wise sum


In [6]:
#Create an array of 10 product prices and apply 15% discount

import numpy as np

prices = np.array([500, 750, 1200, 1500, 2000, 2500, 3000, 3500, 4000, 4500])
discounted_prices = prices * 0.85   # 15% discount

discounted_prices

array([ 425. ,  637.5, 1020. , 1275. , 1700. , 2125. , 2550. , 2975. ,
       3400. , 3825. ])

In [7]:
#Filter orders greater than 1000

orders = np.array([300, 800, 1200, 450, 1800, 2200, 999, 1500])

high_value_orders = orders[orders > 1000]

high_value_orders


array([1200, 1800, 2200, 1500])

In [8]:
# Create 3×3 matrix & calculate row-wise and column-wise sum

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

row_sum = matrix.sum(axis=1)   # Row-wise sum
col_sum = matrix.sum(axis=0)   # Column-wise sum

row_sum, col_sum


(array([ 60, 150, 240]), array([120, 150, 180]))